//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaProject.API.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesOfValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesOfValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzaProject.API.Infrastructure.Localization.MessagesOfValidation", typeof(MessagesOfValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ამ აიდით იუზერზე მისამართი ვერ მოიძებნა .
        /// </summary>
        public static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კალორიების ველი არ შეიძლება იყოს 0-ის ტოლი.
        /// </summary>
        public static string CaloryCountLength {
            get {
                return ResourceManager.GetString("CaloryCountLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კალორიების ველი  არ უნდა იყოს ცარიელი.
        /// </summary>
        public static string CaloryCountMandatoryField {
            get {
                return ResourceManager.GetString("CaloryCountMandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქალაქის ველი უნდა იყოს 1-დან 15 სიმბოლომდე.
        /// </summary>
        public static string CityLength {
            get {
                return ResourceManager.GetString("CityLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქალაქის ველი არ უნდა იყოს ცარიელი.
        /// </summary>
        public static string CityMandatoryField {
            get {
                return ResourceManager.GetString("CityMandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქვეყნის ველი უნდა იყოს 1-დან 15 სიმბოლომდე.
        /// </summary>
        public static string CountryLength {
            get {
                return ResourceManager.GetString("CountryLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქვეყნის ველი არ უნდა იყოს ცარიელი.
        /// </summary>
        public static string CountryMandatoryField {
            get {
                return ResourceManager.GetString("CountryMandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აღწერის ველი უნდა იყოს 100 სიმბოლოზე ნაკლები.
        /// </summary>
        public static string DescriptionLength {
            get {
                return ResourceManager.GetString("DescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to იმეილის ფორმატი არასწორია.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to იმეილი არ უნდა იყოს ცარიელი.
        /// </summary>
        public static string EmailMandatoryField {
            get {
                return ResourceManager.GetString("EmailMandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელის ველი უნდა იყოს 2-დან 20 სიმბოლომდე.
        /// </summary>
        public static string FirstNameLength {
            get {
                return ResourceManager.GetString("FirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელის ველი არ უნდა იყოს ცარიელი.
        /// </summary>
        public static string FirstNameMandatoryField {
            get {
                return ResourceManager.GetString("FirstNameMandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვარის ველი უნდა იყოს 2-დან 30 სიმბოლომდე.
        /// </summary>
        public static string LastNameLength {
            get {
                return ResourceManager.GetString("LastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვარის ველი არ უნდა იყოს ცარიელი.
        /// </summary>
        public static string LastNameMandatoryField {
            get {
                return ResourceManager.GetString("LastNameMandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userId სავალდებულო ველია.
        /// </summary>
        public static string MandatorUserId {
            get {
                return ResourceManager.GetString("MandatorUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელის ველი უნდა იყოს 3-დან 20 სიმბოლომდე.
        /// </summary>
        public static string NameLength {
            get {
                return ResourceManager.GetString("NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელის ველი არ უნდა იყოს ცარიელი.
        /// </summary>
        public static string NameMandatoryField {
            get {
                return ResourceManager.GetString("NameMandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მობილური ნომერის ფორმატი არასწორია.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნომერი არ უნდა იყოს ცარიელი.
        /// </summary>
        public static string PhoneMandatoryField {
            get {
                return ResourceManager.GetString("PhoneMandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პიცისი აიდი სავალდებულო ველია.
        /// </summary>
        public static string PizzaIdMandatory {
            get {
                return ResourceManager.GetString("PizzaIdMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფასი არ შეიძლება იყოს 0-ის ტოლი.
        /// </summary>
        public static string PriceLength {
            get {
                return ResourceManager.GetString("PriceLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფასის ველი არ უნდა იყოს ცარიელი.
        /// </summary>
        public static string PriceMandatoryField {
            get {
                return ResourceManager.GetString("PriceMandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეფასება უნდა იყოს 1-დან 10-მდე.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეფასება ა რუნდა იყოს ცარიელი.
        /// </summary>
        public static string RankMandatoryField {
            get {
                return ResourceManager.GetString("RankMandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to რეგიონის ველი უნდა იყოს 1-დან 15 სიმბოლომდე.
        /// </summary>
        public static string RegionLength {
            get {
                return ResourceManager.GetString("RegionLength", resourceCulture);
            }
        }
    }
}
